name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Linux-x64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and Configure Deployment Mode
      run: dotnet publish -c Release -r linux-x64 -p:PublishReadyToRun=true "Chat Client.sln"
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          My comment
          On this release
          before exiting
          draft
        draft: true
        prerelease: false

  Windows-build:
    
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and Configure Deployment Mode
      run: dotnet publish -c Release -r win-x64 -p:PublishReadyToRun=true "Chat Client.sln"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          My comment
          On this release
          before exiting
          draft
        draft: true
        prerelease: false
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
