name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Linux-x64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and Configure Deployment Mode
      run: dotnet publish -c Release -r linux-x64 -p:PublishReadyToRun=true "Chat Client.sln"
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal

  Windows-build:
    
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and Configure Deployment Mode
      run: dotnet publish -c Release -r win-x64 -p:PublishReadyToRun=true "Chat Client.sln"
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
